# YML version
version: '3'

# Define all the services our book application needs
services:
  server:  # node application
    platform: linux/x86_64
    restart: always # automatically restart if the app fails
    build: ../server
    environment: # environment variables
      # - IP_ADDRESS=192.168.1.172
      - POPCORN_API_BASE_URL_ONE=https://popcorn-time.ga
    ports:
      - '4000:4000' # map the ports as <host-port>:<container-port . The container-port should be the same as the PORT defined in environment.
    command: sh -c "yarn serve"
  app:  # node application
    platform: linux/x86_64
    restart: always # automatically restart if the app fails
    build: . # build the image from the dockerfile present in the current directory
    environment: # environment variables
      - APP_SERVER_BASE_URL=http://localhost:4000
      - APP_TMDB_API_KEY=66683917a94e703e14ca150023f4ea7c
    ports:
      - '8080:8080' # map the ports as <host-port>:<container-port . The container-port should be the same as the PORT defined in environment.
    depends_on:
      - server
    command: sh -c "npm run serve"